#!/usr/bin/env python3
"""
Build practice question bank for anesthesia NP exam prep.
Questions follow 衛福部 麻醉科專科護理師甄審 format and are grounded in:
  - Miller's Anesthesia 8/e
  - Barash Clinical Anesthesia 8/e
  - Nagelhout Nurse Anesthesia 6/e
  - Stoelting's Anesthesia and Co-existing Disease 7/e
  - MGH Clinical Anesthesia Procedures 9/e
  - Hagberg & Benumof Airway Management 4/e
  - Chestnut's Obstetric Anesthesia 6/e
  - Pocket Anesthesia 3/e
"""
import json
from textwrap import dedent

# Category code: BS = Basic Sciences, EQ = Equipment, GP = General Principles, SP = Surgical Procedures/Special Pop
Q = []
def add(cat, sub, stem, opts, ans, summary, points, kw, src):
    qid = f"P-{cat}-{len(Q)+1:03d}"
    Q.append({
        "id": qid,
        "year": "練習",
        "specialty": "anesth_practice",
        "type": "practice",
        "category": cat,
        "subcategory": sub,
        "stem": stem.strip(),
        "options": [{"key": k, "text": v.strip()} for k, v in opts],
        "answer": ans,
        "answerText": dict(opts)[ans].strip(),
        "explanation": {
            "summary": summary.strip(),
            "points": [p.strip() for p in points],
            "keyword": kw.strip(),
        },
        "source": src.strip(),
    })

# ===== BASIC SCIENCES (BS) - 25% target ~20 questions =====

# --- Anatomy / Physiology / Pathophysiology (10) ---
add("BS", "心血管生理",
    "下列關於成人冠狀動脈灌流壓 (Coronary Perfusion Pressure, CPP) 的敘述，何者最為正確？",
    [("A", "CPP = MAP − CVP，於收縮期最大"),
     ("B", "CPP = Aortic Diastolic Pressure − LV End-diastolic Pressure，於舒張期最大"),
     ("C", "CPP = Systolic BP − PA Wedge Pressure，與心跳無關"),
     ("D", "CPP = MAP − ICP，於心跳過慢時最低")],
    "B",
    "左心室冠脈血流主要在舒張期；故 CPP = Diastolic Aortic P − LVEDP。心跳過快會縮短舒張期，是冠心病人術中低血壓必須避免心搏過速的主因。",
    ["右冠則於收縮舒張期均有灌流",
     "Tachycardia + Hypotension + LV hypertrophy 是經典的 subendocardial ischemia 危險組合",
     "維持 Diastolic BP > 60 mmHg 是基本目標"],
    "Coronary Perfusion Pressure, LVEDP",
    "Miller's Anesthesia 8/e, Ch. 25 Cardiovascular Physiology"),

add("BS", "呼吸生理",
    "依 alveolar gas equation，當 FiO₂ = 0.21、PaCO₂ = 40 mmHg、R = 0.8，海平面成年人預期之 PAO₂ 約為多少 mmHg？",
    [("A", "60 mmHg"), ("B", "80 mmHg"), ("C", "100 mmHg"), ("D", "150 mmHg")],
    "C",
    "PAO₂ = FiO₂ × (Patm − PH₂O) − PaCO₂ / R = 0.21 × (760 − 47) − 40/0.8 ≈ 150 − 50 = 100 mmHg。",
    ["A-a gradient 正常 ≤ 10–15 (年輕) 至 30 mmHg (老年)",
     "FiO₂ 提高時 PAO₂ 上升，可用於評估真實 shunt",
     "若 PaO₂ 顯著低於預期 PAO₂，代表 V/Q mismatch、shunt 或 diffusion impairment"],
    "Alveolar gas equation, A-a gradient",
    "Barash Clinical Anesthesia 8/e, Ch. 13 Respiratory Physiology"),

add("BS", "呼吸生理",
    "下列何種情況會使氧合血紅素解離曲線 (Oxyhemoglobin Dissociation Curve) 向右偏移？",
    [("A", "低體溫"), ("B", "血液 pH 上升"), ("C", "2,3-DPG 上升"), ("D", "CO 中毒")],
    "C",
    "右偏 = P50 上升 = 對 O₂ 親和力下降，組織釋氧增加。誘因為發燒、酸中毒、PaCO₂ 上升、2,3-DPG 上升（慢性貧血、高海拔、Thyrotoxicosis）。",
    ["右偏記憶口訣：CADET face Right — CO₂↑、Acid↑、2,3-DPG↑、Exercise、Temperature↑",
     "CO 中毒造成左偏（O₂ 卸載困難）",
     "左偏：低溫、鹼血症、Fetal Hb"],
    "Oxyhemoglobin curve, P50, 2,3-DPG",
    "Miller's Anesthesia 8/e, Ch. 27 Respiratory Function"),

add("BS", "腎臟生理",
    "正常成人腎臟血流量 (Renal Blood Flow, RBF) 約佔心輸出量 (Cardiac Output) 的多少？",
    [("A", "5%"), ("B", "10%"), ("C", "20%"), ("D", "35%")],
    "C",
    "腎臟血流約占 CO 的 20–25%（約 1.0–1.2 L/min）。在 MAP 80–180 mmHg 範圍內，RBF 由 autoregulation 維持穩定；MAP < 80 mmHg 時 GFR 顯著下降，是術中 AKI 的危險因子。",
    ["GFR ≈ 125 mL/min",
     "腎皮質吸收 RBF 的 85–90%；髓質僅 10–15%",
     "麻醉藥多會使 RBF、GFR 下降，正壓通氣亦會降低"],
    "Renal blood flow, autoregulation",
    "Stoelting's Pharmacology & Physiology 5/e, Ch. Renal"),

add("BS", "神經生理",
    "下列何者最能反映腦灌流壓 (Cerebral Perfusion Pressure, CPP) 的計算式？",
    [("A", "CPP = MAP + ICP"),
     ("B", "CPP = MAP − ICP"),
     ("C", "CPP = MAP − CVP"),
     ("D", "CPP = Systolic BP − ICP")],
    "B",
    "CPP = MAP − ICP（若 CVP > ICP 則改用 CVP）。正常 CPP 應維持 50–70 mmHg；TBI 病人建議維持 60–70 mmHg 以避免 secondary brain injury。",
    ["ICP > 20 mmHg 即視為顱內高壓",
     "Cerebral Autoregulation 範圍 MAP 50–150 mmHg；慢性高血壓病人曲線右移",
     "PaCO₂ 每升 1 mmHg，CBF 增加約 4%"],
    "Cerebral perfusion pressure, autoregulation",
    "Miller's Anesthesia 8/e, Ch. 70 Neurosurgical Anesthesia"),

add("BS", "肝臟生理",
    "下列關於肝臟血流之敘述，何者正確？",
    [("A", "肝動脈與門靜脈各提供肝臟氧供約 50%"),
     ("B", "肝動脈提供約 25% 血流但 50% 氧供"),
     ("C", "門靜脈血流壓力高、含氧量豐富"),
     ("D", "肝臟血流不受麻醉藥影響")],
    "B",
    "肝動脈占肝臟總血流 25%、占氧供 50%；門靜脈占血流 75%、氧供 50%。揮發性麻醉藥、Hypotension、PEEP、Pneumoperitoneum 都會降低肝血流。",
    ["Hepatic Artery Buffer Response：門靜脈血流下降時肝動脈代償性擴張",
     "Halothane 對肝血流影響最大；Isoflurane/Sevoflurane/Desflurane 影響較小",
     "肝臟疾病病人對藥物代謝、凝血、白蛋白合成都受影響"],
    "Hepatic blood flow, buffer response",
    "Stoelting's Anesthesia and Co-existing Disease 7/e, Ch. Liver"),

add("BS", "自律神經",
    "刺激交感神經 α₁ 受體，會產生下列何種主要生理效應？",
    [("A", "心跳加快、心肌收縮力增加"),
     ("B", "支氣管擴張、子宮鬆弛"),
     ("C", "周邊血管收縮、瞳孔放大"),
     ("D", "胰島素分泌增加")],
    "C",
    "α₁ 主要在血管平滑肌、瞳孔放大肌、膀胱頸：造成 vasoconstriction、mydriasis、urinary retention。Phenylephrine 是純 α₁ agonist 的代表。",
    ["α₂：突觸前抑制 NE 釋放（central sympatholytic，e.g. clonidine、dexmedetomidine）",
     "β₁：心臟（heart rate、contractility）",
     "β₂：支氣管擴張、血管擴張、子宮鬆弛"],
    "Adrenergic receptors, phenylephrine",
    "Stoelting's Pharmacology 5/e, Ch. Autonomic Nervous System"),

add("BS", "內分泌",
    "手術壓力反應 (Surgical Stress Response) 中，下列何種荷爾蒙會減少？",
    [("A", "Cortisol"), ("B", "Catecholamines"), ("C", "Insulin"), ("D", "ADH (Vasopressin)")],
    "C",
    "手術壓力導致 cortisol、catecholamines、glucagon、GH、ADH、aldosterone 均上升；胰島素相對減少 + 周邊 insulin resistance 造成術中高血糖。",
    ["Hyperglycemia 是術中常見現象，與 SSI、心血管事件、傷口癒合相關",
     "Regional anesthesia 較能抑制壓力反應",
     "高劑量 opioid 可顯著抑制 stress response"],
    "Surgical stress response, hyperglycemia",
    "Miller's Anesthesia 8/e, Ch. 24 Endocrine Function"),

add("BS", "病理生理",
    "下列關於敗血性休克 (Septic Shock) 早期血流動力學的描述，何者最為典型？",
    [("A", "高心輸出、低血管阻力、暖週邊"),
     ("B", "低心輸出、高血管阻力、冷週邊"),
     ("C", "高心輸出、高血管阻力、冷週邊"),
     ("D", "低心輸出、低血管阻力、暖週邊")],
    "A",
    "敗血性休克早期屬 distributive shock：vasodilation 造成 SVR 下降、CO 代償性上升；皮膚暖且紅。晚期可進入心肌抑制期 (低 CO)。",
    ["Hypovolemic / Cardiogenic shock：CO 低、SVR 高、冷週邊",
     "Anaphylactic shock 機轉類似 distributive",
     "Norepinephrine 為敗血性休克之首選 vasopressor (Surviving Sepsis 2021)"],
    "Septic shock, distributive shock, SVR",
    "Barash Clinical Anesthesia 8/e, Ch. 53 Critical Care"),

add("BS", "病理生理",
    "下列何者為惡性高熱 (Malignant Hyperthermia, MH) 之分子病理機轉？",
    [("A", "Mitochondrial uncoupling protein 缺陷"),
     ("B", "Ryanodine Receptor (RYR1) 基因突變導致鈣離子持續釋放"),
     ("C", "Acetylcholinesterase 缺乏"),
     ("D", "Pseudocholinesterase 基因突變")],
    "B",
    "MH 為體染色體顯性遺傳，RYR1 基因突變使 sarcoplasmic reticulum 對 volatile anesthetics 或 succinylcholine 過度敏感，Ca²⁺ 大量釋放→持續肌肉收縮、ATP 消耗、產熱、酸中毒、高鉀。",
    ["第一線治療：Dantrolene 2.5 mg/kg IV，必要時重複至累積 10 mg/kg",
     "立即停止揮發性麻醉劑、改 TIVA、100% O₂、過度換氣降 CO₂",
     "Pseudocholinesterase deficiency 則為 succinylcholine 作用延長，與 MH 無關"],
    "Malignant hyperthermia, RYR1, dantrolene",
    "Miller's Anesthesia 8/e, Ch. 43 Malignant Hyperthermia"),

# --- Pharmacology (8) ---
add("BS", "吸入性麻醉藥",
    "下列關於 MAC (Minimum Alveolar Concentration) 之敘述，何者錯誤？",
    [("A", "MAC 隨年齡上升而下降"),
     ("B", "懷孕會降低 MAC"),
     ("C", "急性酒精中毒會降低 MAC"),
     ("D", "Hyperthermia 會降低 MAC")],
    "D",
    "Hyperthermia 會「增加」MAC（每升 1°C 約增 +5%）；Hypothermia 才會降低 MAC。其他降低 MAC 的因素：年齡↑、孕、急性酒精、opioid、α2-agonist、低鈉、低甲狀腺。",
    ["MAC 定義：50% 病人對手術切皮無反應之呼氣末濃度",
     "MAC-awake ≈ 0.3 MAC；MAC-BAR (block adrenergic response) ≈ 1.5 MAC",
     "MAC 不受性別、術中體重變化、麻醉時間長短影響"],
    "MAC, minimum alveolar concentration",
    "Stoelting's Pharmacology 5/e, Ch. Inhaled Anesthetics"),

add("BS", "靜脈麻醉藥",
    "Propofol 用於 induction 時，下列何項副作用最為常見？",
    [("A", "心搏過速與高血壓"),
     ("B", "支氣管痙攣"),
     ("C", "低血壓與呼吸抑制"),
     ("D", "癲癇發作")],
    "C",
    "Propofol 因 SVR ↓、心肌抑制、venodilation，常造成顯著低血壓；呼吸抑制 / apnea 亦常見。其他特點：抗噁心、quick offset、注射痛、PRIS (Propofol Infusion Syndrome) at high dose × long duration。",
    ["減少注射痛：先給 Lidocaine 20–40 mg IV 或選大靜脈",
     "Egg/Soy allergy 並非絕對禁忌（過敏反應極罕見）",
     "PRIS 三聯徵：代謝性酸中毒、橫紋肌溶解、心衰竭"],
    "Propofol, hypotension, PRIS",
    "Nagelhout Nurse Anesthesia 6/e, Ch. IV Anesthetics"),

add("BS", "鴉片類",
    "下列何種鴉片類藥物因組織酯酶代謝，半衰期不受肝腎功能影響？",
    [("A", "Morphine"), ("B", "Fentanyl"), ("C", "Remifentanil"), ("D", "Meperidine (Pethidine)")],
    "C",
    "Remifentanil 由非特異性血漿與組織酯酶代謝，context-sensitive half-time 約 3–4 分鐘不論輸注多久，可用於肝腎衰竭病人；停藥後迅速恢復但需提前準備 multimodal pain control。",
    ["Morphine 代謝物 M6G 在腎衰竭蓄積 → 呼吸抑制延長",
     "Meperidine 代謝物 Normeperidine 蓄積 → 痙攣",
     "Fentanyl 主要肝代謝，肝衰時清除減慢"],
    "Remifentanil, context-sensitive half-time",
    "Stoelting's Pharmacology 5/e, Ch. Opioids"),

add("BS", "神經肌肉阻斷劑",
    "Succinylcholine 100 mg IV 後病人持續肌肉麻痺超過 2 小時，下列何者最可能的原因？",
    [("A", "Malignant Hyperthermia 前驅期"),
     ("B", "Pseudocholinesterase 缺乏 (Dibucaine number 低)"),
     ("C", "高血鉀症"),
     ("D", "Rocuronium 同時殘留")],
    "B",
    "Plasma (pseudo)cholinesterase deficiency 導致 succinylcholine 代謝大幅延長，Dibucaine number 低 (homozygous 約 20)；正常 ≥ 80。處置：持續通氣、鎮靜直到自然恢復；下次麻醉避免 succinylcholine 及 ester local anesthetics。",
    ["Succinylcholine 副作用：高鉀（燒傷/去神經/長期臥床禁忌）、心搏過緩 (兒童)、Myalgia、MH trigger、Bradycardia",
     "正常作用時間 5–10 分鐘",
     "Acquired deficiency：肝病、孕婦、抗膽鹼酯化酶藥物"],
    "Pseudocholinesterase deficiency, Dibucaine number",
    "Miller's Anesthesia 8/e, Ch. 35 Neuromuscular Blockers"),

add("BS", "神經肌肉阻斷劑",
    "Sugammadex 主要用於逆轉下列何種神經肌肉阻斷劑？",
    [("A", "Succinylcholine"),
     ("B", "Cisatracurium"),
     ("C", "Rocuronium 與 Vecuronium"),
     ("D", "Pancuronium")],
    "C",
    "Sugammadex 為 modified γ-cyclodextrin，特異性 encapsulate steroidal NMBA (Rocuronium > Vecuronium)；對 benzylisoquinolinium 類 (Cisatracurium、Atracurium) 無效。",
    ["劑量：moderate block 2 mg/kg；deep block 4 mg/kg；reversal of rocuronium-induced anaphylaxis 16 mg/kg",
     "副作用：anaphylaxis（罕見但需警覺）、bradycardia",
     "避孕藥效力降低，須告知病人"],
    "Sugammadex, cyclodextrin, NMBA reversal",
    "Barash Clinical Anesthesia 8/e, Ch. 21 NMBA"),

add("BS", "局部麻醉藥",
    "下列關於 Local Anesthetic Systemic Toxicity (LAST) 的處置，何者最為正確？",
    [("A", "首選藥物為 Amiodarone 並啟動 ACLS"),
     ("B", "立即給予 20% Intralipid (Lipid Emulsion) 1.5 mL/kg bolus 並啟動高品質 CPR"),
     ("C", "Vasopressin 為心律不整之首選"),
     ("D", "Bupivacaine 中毒應大劑量使用 Lidocaine 治療心律不整")],
    "B",
    "LAST 處置遵循 ASRA 指引：求救、停藥、控制呼吸道與抽搐 (benzodiazepine)、20% Lipid Emulsion 1.5 mL/kg bolus 後 0.25 mL/kg/min 輸注，必要時可再 bolus 至 12 mL/kg；CPR 同時進行；epinephrine ≤ 1 µg/kg；避免 vasopressin、calcium channel blocker、β-blocker、lidocaine。",
    ["Bupivacaine 心毒性最強：難以復甦的 VT/VF",
     "LAST 高風險：濃度高、注射快、誤打入血管、ESRD",
     "預防：超音波導引、test dose、分段注射、總劑量計算"],
    "LAST, lipid emulsion, ASRA",
    "Barash Clinical Anesthesia 8/e, Ch. 22 Local Anesthetics"),

add("BS", "心血管藥物",
    "下列關於 Norepinephrine 的敘述，何者最為正確？",
    [("A", "為純 α-agonist，無心臟作用"),
     ("B", "α₁ + β₁ 均有作用，可同時增加 SVR 與 contractility"),
     ("C", "首選用於 anaphylactic shock"),
     ("D", "可經周邊靜脈長時間輸注無組織壞死風險")],
    "B",
    "Norepinephrine 同時作用於 α₁ (vasoconstriction) 與 β₁ (inotropy)；為敗血性休克之 first-line vasopressor。Anaphylaxis 首選 Epinephrine。長時間周邊輸注可造成 extravasation 壞死，宜經中心靜脈。",
    ["Phenylephrine：純 α₁，可導致 reflex bradycardia",
     "Epinephrine：α + β₁ + β₂；anaphylaxis、cardiac arrest 首選",
     "Vasopressin：作用於 V1，敗血性休克的 second-line"],
    "Norepinephrine, vasopressor",
    "Stoelting's Pharmacology 5/e, Ch. Sympathomimetics"),

add("BS", "藥物動力學",
    "下列何者最能描述 Context-Sensitive Half-Time (CSHT)？",
    [("A", "藥物從體內完全清除所需時間"),
     ("B", "藥物到達穩態之時間"),
     ("C", "停止輸注後血中藥物濃度下降 50% 所需時間，與輸注時間長短有關"),
     ("D", "口服藥物之 bioavailability")],
    "C",
    "CSHT 對 TIVA、輸注鎮靜很重要：例如 Fentanyl 輸注 6 小時 CSHT 可達 200+ 分鐘；Remifentanil 不論輸注多久 CSHT 始終 3–4 分鐘。Propofol CSHT 隨時間緩慢上升但仍快於 fentanyl。",
    ["藥物 lipid solubility、redistribution、clearance 影響 CSHT",
     "TIVA 用 Propofol + Remifentanil 是 quick offset 的經典組合",
     "ICU 長期輸注 midazolam、fentanyl 會出現顯著延長"],
    "Context-sensitive half-time, TIVA",
    "Miller's Anesthesia 8/e, Ch. 29 Pharmacokinetics"),

# --- Applied Chemistry / Physics (2) ---
add("BS", "物理",
    "依 Poiseuille 定律，下列何項改變會「最」大幅增加靜脈輸液速率？",
    [("A", "輸液管路長度減半"),
     ("B", "靜脈管路內徑加倍"),
     ("C", "輸液壓力 (高度) 加倍"),
     ("D", "輸液黏度減半")],
    "B",
    "Poiseuille's law: Q = π·ΔP·r⁴ / (8·η·L)。流量與半徑「四次方」成正比，故半徑加倍 → 流量增加 16 倍，遠大於其他選項。",
    ["大量輸液應選大口徑短管路 (e.g. 14G/16G、Cordis)",
     "輸液加壓袋、Level 1 等快速輸液裝置應用此原理",
     "臨床：18G > 20G > 22G 流速差異顯著"],
    "Poiseuille's law, IV access",
    "Pocket Anesthesia 3/e, Ch. Physics"),

add("BS", "化學/物理",
    "Soda lime (鹼石灰) 與 Sevoflurane 反應產生之 Compound A，於下列何種情況下產量會增加？",
    [("A", "低流速 (low fresh gas flow)、乾燥的 absorbent"),
     ("B", "高流速 + 濕潤的 absorbent"),
     ("C", "使用 Desflurane"),
     ("D", "使用 Calcium hydroxide 為基底的 absorbent (Amsorb)")],
    "A",
    "Compound A 在 low-flow、乾燥、含 strong base (NaOH/KOH) 的 absorbent、高溫下產生最多；可能對腎臟有毒（動物實驗）。建議 Sevoflurane low-flow 時 ≥ 1 L/min 或 ≥ 2 MAC-hour 限制；Amsorb (CaOH₂) 幾乎不產生 Compound A。",
    ["Desflurane 在乾燥 Baralyme 與 NaOH/KOH soda lime 可產生 CO，特別是節假日後第一台",
     "新世代 absorbent (Amsorb、Litholyme) 較安全",
     "Wet absorbent 反而較不產 Compound A"],
    "Sevoflurane, Compound A, soda lime",
    "Miller's Anesthesia 8/e, Ch. 30 Inhaled Anesthetics"),

# ===== EQUIPMENT / INSTRUMENTATION (EQ) - 15% target ~12 questions =====

# --- Anesthesia Delivery Systems (4) ---
add("EQ", "麻醉機",
    "現代麻醉機之 oxygen failure safety device (Fail-safe valve) 主要功能為何？",
    [("A", "當 N₂O 中斷時自動補充 O₂"),
     ("B", "當 O₂ pipeline 壓力下降時，自動關閉或降低 N₂O 與其他氣體流量"),
     ("C", "當 CO₂ absorbent 耗盡時自動切換 fresh canister"),
     ("D", "偵測 disconnection 並自動恢復通氣")],
    "B",
    "Fail-safe valve 依 O₂ supply pressure 控制其他氣體流量；O₂ 壓力 < 30 psi 時切斷 N₂O 等氣體，避免病人接受低氧氣體混合。但「不保證」FiO₂ ≥ 21%，仍需 hypoxic guard (O₂/N₂O proportioning system, e.g. Ohmeda Link 25)。",
    ["Pin index system 防止氣瓶接錯",
     "DISS (Diameter Index Safety System) 防止 pipeline 接錯",
     "O₂ analyzer 為最後一道防線，必須每次術前校正"],
    "Anesthesia machine safety, fail-safe",
    "Dorsch Understanding Anesthesia Equipment 5/e"),

add("EQ", "麻醉機",
    "麻醉前儀器檢查 (Pre-anesthetic Machine Checkout) 中，下列何項可偵測 high-pressure system leak？",
    [("A", "Negative pressure leak test"),
     ("B", "O₂ flush test"),
     ("C", "Sodalime 顏色變化"),
     ("D", "關閉所有氣瓶後觀察壓力錶下降速度")],
    "D",
    "關閉氣瓶後觀察 cylinder/pipeline pressure gauge 下降速率為標準 high-pressure leak test。Low-pressure system (vaporizer → common gas outlet) leak 則需 negative pressure (suction bulb) test。",
    ["FDA 麻醉機檢查 14 項中，包含 O₂ analyzer 校正、leak test、breathing system、scavenging、ventilator、suction、emergency O₂",
     "Vaporizer 應 ≥ 1/4 滿、無傾倒",
     "每位病人之間需執行 abbreviated check"],
    "Machine checkout, leak test",
    "Ehrenwerth Anesthesia Equipment 2/e"),

add("EQ", "呼吸迴路",
    "Circle system 中 unidirectional valve 失效，會造成下列何種問題？",
    [("A", "肺水腫"), ("B", "Rebreathing 與 hypercapnia"),
     ("C", "高 FiO₂ alarm"), ("D", "Compound A 大量產生")],
    "B",
    "Unidirectional (one-way) valve sticky 或失效 → 病人吐氣再被吸入 → CO₂ rebreathing → ETCO₂ baseline 升高 (而非單純 PaCO₂↑)。Capnograph 出現 inspired CO₂ > 0 為典型徵兆。",
    ["檢查：機器自我檢測、direct visualization",
     "處置：立刻改用 Mapleson D / Bag-Mask 通氣，呼叫工程",
     "其他 rebreathing 原因：absorbent 耗盡、bypass valve 位置錯誤"],
    "Circle system, unidirectional valve, rebreathing",
    "Dorsch Understanding Anesthesia Equipment 5/e"),

add("EQ", "Capnography",
    "病人術中 ETCO₂ 從 35 mmHg 突然降到 12 mmHg，呼吸音消失、SpO₂ 開始下降。下列何者為最可能的原因？",
    [("A", "ETT 進入右主支氣管"),
     ("B", "ETT 脫位至食道 (esophageal intubation) 或 circuit disconnection"),
     ("C", "Hypercapnia"),
     ("D", "肺栓塞")],
    "B",
    "ETCO₂ 突降至接近 0 + 呼吸音消失 = circuit disconnect、ETT 拔出、或 ventilator/airway 失效。應立即直接喉鏡或胸壁觀察並重新評估呼吸道。肺栓塞 ETCO₂ 也會下降但通常較緩、伴循環不穩。",
    ["Capnography 為 ETT 位置確認的金標準",
     "Right mainstem intubation 通常 ETCO₂ 不變，但 peak airway pressure 上升、單側肺音",
     "MH 與 hypercapnia 會使 ETCO₂ 急升"],
    "Capnography, esophageal intubation",
    "Hagberg Airway Management 4/e"),

# --- Airway Equipment (3) ---
add("EQ", "呼吸道器材",
    "下列何項為 Laryngeal Mask Airway (LMA) Classic 之絕對禁忌？",
    [("A", "短期外科手術 < 2 小時"),
     ("B", "未禁食或腸阻塞之飽肚病人"),
     ("C", "OSA 病人手術"),
     ("D", "BMI 25 之肥胖病人")],
    "B",
    "LMA Classic 不能可靠保護 airway 對抗 aspiration，非禁食、腸阻塞、孕婦、嚴重 GERD 為相對/絕對禁忌；trauma surgery、prone position、long surgery 也需謹慎。",
    ["LMA ProSeal、Supreme 提供 drain tube，可吸引胃內容物，仍非完全保護",
     "Difficult airway algorithm 中 LMA 為 rescue device",
     "LMA 適合短時間自主呼吸的中小手術"],
    "LMA, aspiration",
    "Hagberg Airway Management 4/e"),

add("EQ", "呼吸道器材",
    "下列何者為成人 video laryngoscope (e.g. GlideScope) 使用之關鍵注意事項？",
    [("A", "插管時應將鏡片放至更深的會厭谷"),
     ("B", "需專用造型 stylet 之 ETT，避免硬塞"),
     ("C", "完全取代直接喉鏡，不需常備 DL"),
     ("D", "不適用於困難呼吸道")],
    "B",
    "Video laryngoscope 雖讓 glottis 視野改善，但 ETT 推進角度受限，需專用 60° 弧度 stylet 或 hyperangulated blade 配對之 stylet，硬推可能造成 palatal/pharyngeal injury。應預備 stylet 並掌握角度。",
    ["GlideScope、C-MAC、McGrath 均屬此類，視野好但推管難",
     "DAS 2015 指引：Plan B 可考慮 VL；困難呼吸道仍需備 Bougie、LMA、cricothyroidotomy",
     "Awake VL 適用於預期困難呼吸道"],
    "Video laryngoscope, stylet",
    "Hagberg Airway Management 4/e"),

add("EQ", "困難呼吸道",
    "依 DAS / ASA 困難呼吸道演算法，無法插管、無法通氣 (CICO: Can't Intubate, Can't Oxygenate) 之最後救援步驟為何？",
    [("A", "再嘗試直接喉鏡 3 次"),
     ("B", "Front of neck access — Cricothyroidotomy"),
     ("C", "改用 awake fiberoptic"),
     ("D", "立即 Reverse NMBA")],
    "B",
    "CICO 為 emergency airway，DAS 2015 建議使用 scalpel-bougie-tube 技術做 cricothyroidotomy；不應再延誤嘗試其他方式。早期啟動、明確角色分工 (declare CICO)。",
    ["Surgical cricothyroidotomy > needle (兒童 < 12 歲考慮 needle + jet)",
     "預防為主：預測困難呼吸道 → awake intubation、清醒準備",
     "Sugammadex 反轉 rocuronium 也可於 CICO 但不可延誤 FONA"],
    "Cricothyroidotomy, CICO, DAS algorithm",
    "Hagberg Airway Management 4/e"),

# --- Monitoring (4) ---
add("EQ", "標準監測",
    "ASA standard basic monitoring 不包括下列何者？",
    [("A", "持續心電圖"), ("B", "脈搏血氧 (SpO₂)"),
     ("C", "持續 invasive arterial blood pressure"),
     ("D", "體溫")],
    "C",
    "ASA standard 包括：氧合 (FiO₂ + SpO₂)、通氣 (capnography + spirometry)、循環 (EKG + 血壓至少每 5 分鐘 + 持續心跳)、體溫（合理預期溫度改變時）。Invasive A-line 非 standard，依手術病人需要。",
    ["Capnography 為必備 (qualitative + quantitative)",
     "Anesthesia 人員必須在場全程",
     "麻醉前需有功能性 PPV alarm"],
    "ASA standards, monitoring",
    "ASA Standards for Basic Anesthetic Monitoring"),

add("EQ", "血流動力學監測",
    "下列何種波形分析可估算 Cardiac Output 與 fluid responsiveness？",
    [("A", "Standard 5-lead EKG"),
     ("B", "Arterial pulse contour analysis (FloTrac, PiCCO)"),
     ("C", "Pulse oximeter waveform"),
     ("D", "End-tidal CO₂ waveform")],
    "B",
    "Arterial pulse contour analysis 透過動脈波形 (area under systolic ejection) 估算 stroke volume、CO，並可計算 SVV (stroke volume variation) 評估 fluid responsiveness (SVV > 13% 通常表示 volume responsive，但需 controlled ventilation、TV ≥ 8 mL/kg、sinus rhythm)。",
    ["PA catheter 仍為 cardiac output 金標準，但已較少使用",
     "TEE 為心臟手術主要監測工具",
     "POCUS (IVC、LV function) 應用日增"],
    "Pulse contour, SVV, fluid responsiveness",
    "Miller's Anesthesia 8/e, Ch. 45 Monitoring"),

add("EQ", "BIS",
    "Bispectral Index (BIS) 監測之適當麻醉深度範圍為何？",
    [("A", "0–20"), ("B", "40–60"), ("C", "70–90"), ("D", "90–100")],
    "B",
    "BIS 0 = isoelectric EEG；100 = 完全清醒。General anesthesia 適當範圍 40–60。BIS 可減少 awareness、減少 anesthetic 用量；但於 TIVA、TIVA-only 麻醉、高風險 awareness 病人 (e.g. 心臟手術、obstetric) 特別有用。",
    ["EMG artifact、低體溫、ketamine、N₂O 可影響 BIS reading",
     "BIS ≠ pain monitor",
     "Patient State Index (PSI)、Entropy 為替代方案"],
    "BIS, depth of anesthesia",
    "Miller's Anesthesia 8/e, Ch. 50 Awareness"),

add("EQ", "神經肌肉監測",
    "Train-of-Four (TOF) ratio T4/T1 達到下列何數值，可視為適合拔管？",
    [("A", "T4/T1 > 0.4"), ("B", "T4/T1 > 0.6"),
     ("C", "T4/T1 > 0.7"), ("D", "T4/T1 ≥ 0.9")],
    "D",
    "現行標準：TOF ratio ≥ 0.9 方視為 adequate recovery，避免 residual neuromuscular blockade (RNMB) 引起 hypoxia、aspiration、上呼吸道阻塞、reintubation。客觀量測 (acceleromyography, electromyography) 優於主觀觀察。",
    ["TOF count 0–4，視 receptor 占有率",
     "Sugammadex 可逆轉 rocuronium 至 TOF ≥ 0.9",
     "Neostigmine + glycopyrrolate 需 TOF count ≥ 2 才有效"],
    "TOF ratio, residual blockade",
    "Barash Clinical Anesthesia 8/e, Ch. 21 NMBA"),

# --- Imaging (1) ---
add("EQ", "超音波",
    "超音波導引週邊靜脈或神經阻斷時，下列何種探頭最常使用？",
    [("A", "Phased array (心臟探頭) 1–5 MHz"),
     ("B", "Linear high-frequency 6–15 MHz"),
     ("C", "Curvilinear 2–5 MHz"),
     ("D", "Endocavitary 5–9 MHz")],
    "B",
    "週邊神經、表淺血管位於 1–6 cm 深度，高頻 linear probe 解析度佳；深部結構 (e.g. abdominal、Cardiac) 用低頻 curvilinear / phased array。",
    ["超音波導引降低 LAST、神經損傷、血管刺穿風險",
     "需練習 in-plane vs out-of-plane 兩種針徑顯影法",
     "Hydrodissection、Doppler 確認血流為實用技巧"],
    "Ultrasound, regional anesthesia, transducer",
    "Brown's Atlas of Regional Anesthesia 5/e"),

# ===== GENERAL PRINCIPLES (GP) - 30% target ~24 questions =====

# --- Ethics / Legal (2) ---
add("GP", "知情同意",
    "下列關於麻醉知情同意 (Informed Consent) 之原則，何者最為適當？",
    [("A", "病人簽署同意書即代表 informed consent 完成"),
     ("B", "需告知麻醉方式、風險、益處及替代方案；病人有理解與自主決定能力"),
     ("C", "病人為精神病可由配偶代為同意，無須評估病人能力"),
     ("D", "緊急手術不必告知任何資訊")],
    "B",
    "Informed Consent 四要素：disclosure (適當資訊)、understanding (理解)、voluntariness (自願)、capacity (能力)。緊急且 life-threatening 可援用 implied consent；無能力病人由 surrogate decision-maker。",
    ["Anesthesia consent 應與外科同意分開",
     "Jehovah's Witness 對輸血的選擇須於術前明確記錄",
     "未成年人之 informed consent 由監護人，惟逐步年齡可給予 assent"],
    "Informed consent, capacity",
    "Barash Clinical Anesthesia 8/e, Ch. 1 Anesthesia Practice"),

add("GP", "法律",
    "下列關於 Do-Not-Resuscitate (DNR) order 於手術期間之處理，何者最為正確？",
    [("A", "DNR 病人不可接受任何手術"),
     ("B", "進入手術室應自動暫停 DNR"),
     ("C", "需於術前與病人/家屬重新確認 DNR 範圍，明確記錄 (Required Reconsideration)"),
     ("D", "麻醉醫師可單方面決定是否執行 DNR")],
    "C",
    "ASA 建議：DNR 病人於手術前須 Required Reconsideration，與病人/家屬討論並選擇：(1) full resuscitation、(2) limited based on procedure、(3) limited based on goals。決議須明確記錄並於 PACU 後重新評估。",
    ["不可單方面暫停 DNR，違反病人自主",
     "若臨床決策衝突，倫理委員會 / palliative care 諮詢",
     "Anesthesia-related 心搏停止 (e.g. medication error) 通常可救援"],
    "DNR, Required Reconsideration",
    "Miller's Anesthesia 8/e, Ch. 14 Ethics"),

# --- Safety (2) ---
add("GP", "安全",
    "下列關於 WHO Surgical Safety Checklist 之敘述，何者錯誤？",
    [("A", "麻醉開始前進行 Sign In"),
     ("B", "皮膚切開前進行 Time Out"),
     ("C", "病人離開手術室前進行 Sign Out"),
     ("D", "團隊任何成員無權暫停手術以提出 concerns")],
    "D",
    "WHO Checklist 強調團隊任何成員都有 stop the line 權利。Sign In (麻醉前)、Time Out (切皮前) 與 Sign Out (病人離室前) 是減少手術錯誤、提升安全文化的重要工具。",
    ["Time Out 確認：病人身分、手術名稱、部位、輸血需求、抗生素時機",
     "Universal Protocol 由 The Joint Commission 制訂",
     "Closed-loop communication 為核心溝通技巧"],
    "WHO Checklist, Time Out, surgical safety",
    "WHO Surgical Safety Checklist 2nd edition"),

add("GP", "OR 火災安全",
    "Operating Room Fire Triangle 包含下列何三者？",
    [("A", "Oxidizer + Fuel + Ignition source"),
     ("B", "Electricity + Water + Alcohol"),
     ("C", "Laser + Oxygen + Surgeon"),
     ("D", "Plastic + Heat + Wind")],
    "A",
    "Fire triangle：Oxidizer (O₂、N₂O)、Fuel (drape、ETT、alcohol prep)、Ignition (electrocautery、laser、fiberoptic)。高風險手術 (face/neck) 應使用最低 FiO₂ (< 30%)、避免 alcohol prep 未乾燥、laser 手術選用 laser-resistant ETT。",
    ["氣道火災處置：停止 ventilation、拔 ETT、停止氣體、生理食鹽水滅火",
     "燒傷後檢查氣道熱傷害、CO 中毒",
     "ASA Fire Algorithm 應每年訓練"],
    "OR fire, oxygen, electrocautery",
    "Barash Clinical Anesthesia 8/e, Ch. 17 Patient Safety"),

# --- Preoperative Assessment (4) ---
add("GP", "ASA 分級",
    "75 歲男性，控制良好高血壓、Type 2 DM、輕度 COPD，預定 elective 膝關節置換。最適合的 ASA Physical Status 為何？",
    [("A", "ASA I"), ("B", "ASA II"), ("C", "ASA III"), ("D", "ASA IV")],
    "C",
    "ASA III 定義：嚴重系統性疾病但未失能 (substantive functional limitations)。糖尿病 + 高血壓 + COPD 雖控制，仍多重慢性病。年齡本身不單獨升等。",
    ["ASA I：健康；II：mild systemic disease 無功能限制",
     "ASA IV：constant threat to life；V：moribund；VI：腦死器捐",
     "Emergency (E) 加註於任何級別"],
    "ASA Physical Status",
    "ASA Physical Status Classification System"),

add("GP", "NPO 指引",
    "依 ASA 2017 Practice Guidelines for Preoperative Fasting，下列何者錯誤？",
    [("A", "清液 (Clear liquids) 至麻醉前 2 小時"),
     ("B", "母乳至麻醉前 4 小時"),
     ("C", "嬰兒配方奶至麻醉前 6 小時"),
     ("D", "輕食 (light meal) 至麻醉前 4 小時")],
    "D",
    "Light meal (toast + clear liquid) 至麻醉前 6 小時；fried/fatty/meat 至少 8 小時。Clear liquid 2h、breast milk 4h、infant formula/non-human milk 6h、light meal 6h、heavy meal 8h。",
    ["Clear liquids 不含纖維、酒精、牛奶",
     "口香糖、糖果視為 clear liquid 處理，惟須等同 NPO 規則",
     "GERD、孕婦、糖尿病胃輕癱建議延長"],
    "NPO, fasting guidelines",
    "ASA Practice Guidelines for Preoperative Fasting 2017"),

add("GP", "心臟風險",
    "65 歲病人預定 elective abdominal aortic aneurysm repair，下列何者為最重要的心臟風險評估指標？",
    [("A", "ECG 左軸偏移"),
     ("B", "Revised Cardiac Risk Index (RCRI) 與 functional capacity (METs)"),
     ("C", "Total cholesterol level"),
     ("D", "腦波")],
    "B",
    "ACC/AHA 2014 指引：先評估手術緊急度、active cardiac conditions、RCRI、functional capacity。METs ≥ 4 (e.g. 爬兩層樓) 通常無需進一步檢查；< 4 + 高風險手術 + RCRI ≥ 1 才考慮 stress test。",
    ["RCRI 6 項：high-risk surgery、IHD、HF、CVA、DM on insulin、Cr > 2",
     "AAA repair 屬 high-risk vascular surgery",
     "Stress test 結果不改變處置時不必做"],
    "RCRI, METs, cardiac evaluation",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

add("GP", "抗凝血藥",
    "病人服用 Apixaban 5 mg BID，預定 elective hip replacement，腎功能正常。手術前最少應停藥幾天？",
    [("A", "8 小時"), ("B", "24 小時"),
     ("C", "48 小時 (high bleeding risk surgery)"),
     ("D", "7 天")],
    "C",
    "DOACs (Apixaban、Rivaroxaban、Dabigatran) 於 high bleeding risk surgery 建議停 48–72h (腎功能正常)；low bleeding risk 24h。Dabigatran 高風險 + CrCl 50–80 停 72h、CrCl 30–50 停 96h。",
    ["Warfarin 停 5 天，目標 INR < 1.5",
     "Bridge therapy 僅高血栓風險 (mechanical valve、recent VTE) 才使用",
     "Neuraxial anesthesia 需依 ASRA 指引嚴格停藥時限"],
    "DOAC, anticoagulation, ASRA",
    "ASRA Guidelines for Anticoagulation 4th edition"),

# --- Fluid Management (3) ---
add("GP", "輸液維持",
    "依 Holliday-Segar 公式，25 kg 小兒每日維持輸液量為多少 mL？",
    [("A", "1000 mL"), ("B", "1300 mL"), ("C", "1600 mL"), ("D", "2000 mL")],
    "C",
    "Holliday-Segar：0–10 kg → 100 mL/kg；10–20 kg → 50 mL/kg (>10kg部分)；>20 kg → 20 mL/kg (>20kg部分)。25 kg：1000 + 500 + 100 = 1600 mL/day。換算 hourly 4-2-1 規則：40 + 20 + 5 = 65 mL/hr。",
    ["4-2-1 是每小時版本",
     "兒童脫水評估：mild 5%、moderate 10%、severe 15%",
     "嬰兒對脫水耐受性差，建議用 isotonic fluid"],
    "Holliday-Segar, maintenance fluid",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

add("GP", "輸血指引",
    "下列何種情況最符合 ASA 與 AABB 建議的 RBC 輸血閾值？",
    [("A", "Hb < 10 g/dL 即輸血"),
     ("B", "穩定病人 Hb < 7 g/dL；ACS/心臟手術 Hb < 8 g/dL"),
     ("C", "所有手術病人 Hb < 9 g/dL 即輸血"),
     ("D", "Hct < 35% 即輸血")],
    "B",
    "Restrictive 策略 (Hb 7–8 g/dL) 與 liberal 策略 (Hb 9–10 g/dL) 相比，多數研究顯示 restrictive 不劣於或更佳。心臟手術、ACS 病人採 Hb < 8 g/dL 閾值。",
    ["Massive transfusion：1:1:1 (RBC : FFP : Platelet)",
     "TRALI、TACO、TRIM 為輸血併發症",
     "ROTEM / TEG 引導目標輸血可減少 blood use"],
    "Transfusion threshold, AABB",
    "AABB Guidelines, Stoelting's 7/e"),

add("GP", "液體反應",
    "下列何者為 fluid responsiveness 最佳的動態指標？",
    [("A", "CVP < 8 mmHg"),
     ("B", "PA Wedge Pressure < 12 mmHg"),
     ("C", "Stroke Volume Variation (SVV) > 13% 於 controlled ventilation"),
     ("D", "Urine output < 0.5 mL/kg/hr")],
    "C",
    "Static indicators (CVP、PCWP) 已被證實不可靠；dynamic indicators (SVV、PPV、PVI、PLR test) 更能預測 fluid responsiveness。SVV > 13% 於 TV ≥ 8 mL/kg、sinus rhythm、controlled ventilation 下有效。",
    ["Passive Leg Raise test：抬腿 45° 1 分鐘觀察 CO 變化 ≥ 10%",
     "POCUS IVC 變化 (spontaneous breathing) 亦可參考",
     "高 CVP 不等於 volume overload；低 CVP 也不等於 hypovolemia"],
    "Fluid responsiveness, SVV, PPV",
    "Miller's Anesthesia 8/e, Ch. 59 Fluid Management"),

# --- Positioning (1) ---
add("GP", "擺位",
    "下列何種手術擺位最常見之神經損傷部位為何？",
    [("A", "俯臥 (Prone) — Brachial Plexus"),
     ("B", "Lithotomy — Common Peroneal Nerve"),
     ("C", "Lateral decubitus — Femoral Nerve"),
     ("D", "Beach chair — Radial Nerve")],
    "B",
    "Lithotomy position 最常見 common peroneal nerve injury，因 fibular head 受壓；其次為 saphenous、sciatic nerve。Brachial plexus injury 多見於 Trendelenburg + shoulder brace；Beach chair 易致腦灌流不足。",
    ["Ulnar nerve injury 最常見於 supine + 手臂 abduction、過度旋前",
     "預防：充分 padding、定期重新評估、避免極端 hyperflexion/extension",
     "Compartment syndrome：Lithotomy > 4 hours 風險增加"],
    "Positioning injury, peroneal nerve",
    "Miller's Anesthesia 8/e, Ch. 41 Patient Positioning"),

# --- Data Interpretation (2) ---
add("GP", "血氣分析",
    "病人 ABG：pH 7.22 / PaCO₂ 30 / HCO₃ 12 / PaO₂ 95。下列何者最為正確？",
    [("A", "Acute respiratory acidosis"),
     ("B", "Metabolic acidosis with respiratory compensation"),
     ("C", "Chronic respiratory acidosis"),
     ("D", "Mixed alkalosis")],
    "B",
    "pH < 7.35 為 acidemia；HCO₃ < 22 為 metabolic acidosis；PaCO₂ 降低為 respiratory compensation。可計算 Winter's formula 預期 PaCO₂ = 1.5 × HCO₃ + 8 ± 2 = 26 ± 2，實際 30 略高，suggest 同時 mild respiratory acidosis 或 compensation 不足。",
    ["Anion Gap = Na − (Cl + HCO₃)；正常 8–12",
     "AG metabolic acidosis：DKA、Lactic acidosis、Renal、Toxin",
     "Non-AG：diarrhea、RTA、saline-induced"],
    "ABG interpretation, Winter's formula",
    "Pocket Anesthesia 3/e, Ch. ABG"),

add("GP", "電解質",
    "病人於 TURP 手術後出現意識改變、抽搐，Na 112 mEq/L。最可能診斷為何？",
    [("A", "Hypoglycemia"),
     ("B", "TURP Syndrome (Acute hyponatremia from absorbed irrigation fluid)"),
     ("C", "Septic encephalopathy"),
     ("D", "Air embolism")],
    "B",
    "TURP 使用 glycine、sorbitol、mannitol 沖洗液，可被前列腺血管床吸收 → acute hyponatremia + volume overload + glycine toxicity (visual symptoms)。處置：停止手術、3% NaCl 緩慢矯正、furosemide、ICU 觀察。",
    ["Saline 為導電不能用 monopolar TURP；bipolar TURP 可用 saline 已減少此症",
     "Acute hyponatremia (< 48h) 可較快矯正 (避免 ODS)",
     "Chronic hyponatremia 矯正 ≤ 8–10 mEq/L/day 防 osmotic demyelination"],
    "TURP syndrome, hyponatremia",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

# --- Airway Management (4) ---
add("GP", "預測困難呼吸道",
    "下列何項預測困難插管之敏感度與特異度最為平衡？",
    [("A", "Mallampati class alone"),
     ("B", "Thyromental distance < 6 cm alone"),
     ("C", "LEMON 法則 (Look、Evaluate 3-3-2、Mallampati、Obstruction、Neck mobility)"),
     ("D", "BMI alone")],
    "C",
    "單一指標敏感性低；多參數綜合評估 (LEMON、ALSO-NMK) 較準確。困難呼吸道的危險因子：頸短、頸部活動受限、突出門牙、Mallampati 3-4、開口 < 3 cm、TMD < 6 cm、頸圍 > 43 cm。",
    ["困難 mask ventilation：BONES (Beard、Obesity、No teeth、Elderly、Snoring)",
     "困難 SAD：RODS (Restricted opening、Obesity、Distorted anatomy、Stiff lungs)",
     "預期困難 → awake fiberoptic 或 awake VL"],
    "LEMON, difficult airway prediction",
    "Hagberg Airway Management 4/e"),

add("GP", "RSI",
    "Rapid Sequence Induction (RSI) 的核心要素，下列何者最為正確？",
    [("A", "Pre-oxygenation + Etomidate + Rocuronium + Cricoid pressure (Sellick) — 待自主呼吸消失即插管"),
     ("B", "Slow induction with mask ventilation"),
     ("C", "Use of LMA as first-line"),
     ("D", "Avoid muscle relaxant to keep spontaneous breathing")],
    "A",
    "RSI 目的為盡快取得 secured airway，避免 aspiration：(1) Preoxygenation 3 min 或 8 deep breaths；(2) IV induction (Propofol/Etomidate/Ketamine)；(3) Rapid-onset NMBA (Succinylcholine 1–1.5 mg/kg 或 Rocuronium 1.2 mg/kg)；(4) Cricoid pressure (爭議性，可選)；(5) 無 mask ventilation 直接插管。",
    ["適應症：full stomach、GERD、孕婦、腸阻塞、急救插管",
     "Sellick maneuver 證據力不一，部分機構已不常規使用",
     "兒童 Modified RSI：可給 gentle mask ventilation 預防 hypoxia"],
    "RSI, rapid sequence induction",
    "Hagberg Airway Management 4/e"),

add("GP", "拔管",
    "下列何種情況最不建議立即拔管 (Extubation)？",
    [("A", "意識完全清醒、能執行指令"),
     ("B", "TOF ratio ≥ 0.9"),
     ("C", "深麻醉狀態下，預期病人甦醒前可能 laryngospasm"),
     ("D", "潮氣量 > 6 mL/kg、自主呼吸穩定")],
    "C",
    "Awake extubation 為標準；Deep extubation 可考慮於某些短小手術、reactive airway 病人，但需穩定氣道、無 laryngospasm 風險、且能 mask ventilation。困難呼吸道 + 深麻醉拔管屬高風險。",
    ["拔管前確認：醒、NMB 反轉、體溫正常、肌力恢復、有效咳嗽、保護性反射",
     "拔管失敗的高風險：難插管病人、頸部手術、肥胖、OSA、長時間插管",
     "Extubation algorithm (DAS 2012)：plan、prepare、perform、post-extubation care"],
    "Extubation, awake vs deep",
    "DAS Extubation Guidelines 2012"),

add("GP", "Laryngospasm",
    "兒童麻醉誘導期發生 laryngospasm，最有效的處置為何？",
    [("A", "立即靜脈推注 Atropine"),
     ("B", "正壓 CPAP + 加深麻醉 (Propofol)、必要時 succinylcholine 0.1–0.5 mg/kg"),
     ("C", "立即氣管切開"),
     ("D", "改用 LMA")],
    "B",
    "處置順序：移除刺激、100% O₂ CPAP、jaw thrust + Larson's point pressure、加深麻醉 (Propofol)。持續無法解除 → succinylcholine 0.1–0.5 mg/kg IV (或 IM 4 mg/kg 若無 IV)。若 bradycardia 給 atropine 0.02 mg/kg。",
    ["小兒易發生 laryngospasm 之時機：light anesthesia 拔管、URI、suction",
     "預防：拔管於深麻醉或完全清醒，避免 stage 2",
     "Larson's point：mandible behind earlobe"],
    "Laryngospasm, Larson's point",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

# --- Regional Anesthesia (4) ---
add("GP", "區域麻醉",
    "下列關於 Spinal Anesthesia 與 Epidural Anesthesia 之比較，何者最為正確？",
    [("A", "Spinal 起效慢但範圍可控"),
     ("B", "Epidural 起效較慢、可置管延長作用、滴定容易"),
     ("C", "Spinal 副作用較少"),
     ("D", "Epidural 不會造成 sympathectomy")],
    "B",
    "Epidural：起效 10–20 分鐘、滴定容易、可置管延長作用 (產科分娩鎮痛、術後)；藥量 10×spinal。Spinal：起效 < 5 分鐘、藥量小、不可調整、單次。兩者都會 sympathectomy 引起 hypotension。",
    ["Spinal 給藥：bupivacaine 10–15 mg、ropivacaine、levobupivacaine",
     "Epidural test dose：1.5% lidocaine 3 mL with 1:200,000 epinephrine 檢測 intravascular / intrathecal",
     "PDPH 風險：spinal (cutting needle) > epidural (wet tap)"],
    "Spinal vs epidural, neuraxial",
    "Brown's Atlas of Regional Anesthesia 5/e"),

add("GP", "Neuraxial 禁忌",
    "下列何者為 Neuraxial Anesthesia 之絕對禁忌？",
    [("A", "Aortic stenosis (mild)"),
     ("B", "病人拒絕、注射部位感染、未矯正之凝血異常"),
     ("C", "穩定的高血壓"),
     ("D", "Sickle cell disease")],
    "B",
    "絕對禁忌：病人拒絕、注射部位感染、嚴重凝血異常 / 抗凝藥未停、ICP 增高、嚴重 hypovolemia。相對：嚴重 AS、嚴重脊椎變形、神經疾患。ASRA 抗凝指引嚴格規範各藥物停藥時程。",
    ["Severe AS 已非絕對禁忌，需謹慎、避免 hypotension、考慮 epidural 漸進滴定",
     "Epidural hematoma 發生率低但災難性",
     "抗血小板藥物 (Aspirin) 可繼續；Clopidogrel 停 7 天"],
    "Neuraxial contraindication, ASRA",
    "ASRA Anticoagulation Guidelines 4th edition"),

add("GP", "週邊神經阻斷",
    "Interscalene Block 最常見之副作用為何？",
    [("A", "Phrenic Nerve Block 引起同側橫膈麻痺與呼吸困難"),
     ("B", "Recurrent laryngeal nerve block 引起永久聲音改變"),
     ("C", "Pneumothorax > 30%"),
     ("D", "Cardiac arrest")],
    "A",
    "Interscalene block 100% phrenic nerve block，造成同側 hemidiaphragmatic paresis；嚴重 COPD、單肺、肥胖病人禁忌。其他併發症：Horner、Recurrent laryngeal block (hoarseness)、vertebral artery injection (LAST)、cervical epidural、spinal injection。",
    ["Supraclavicular block phrenic 發生率較低 (50%)",
     "Pneumothorax 風險：supraclavicular > infraclavicular > interscalene",
     "Anatomy 標記：scalene gap、subclavian artery"],
    "Interscalene, phrenic nerve",
    "Brown's Atlas of Regional Anesthesia 5/e"),

add("GP", "硬脊膜外併發症",
    "產婦 epidural 術後 24 小時抱怨嚴重頭痛，坐姿加劇、平躺改善。最可能診斷與處置為何？",
    [("A", "蛛網膜下出血 — 立即 CT"),
     ("B", "Post-Dural Puncture Headache (PDPH) — Conservative + 必要時 Epidural blood patch"),
     ("C", "Cluster headache — 給 100% O₂"),
     ("D", "腦膜炎 — Lumbar puncture")],
    "B",
    "PDPH 典型特徵：postural headache、24–72h 出現、可伴頸僵、視聽症狀。處置：bed rest、hydration、caffeine、analgesia；持續 / severe 給 epidural blood patch (15–20 mL 自體血) 成功率 70–90%。",
    ["PDPH 風險：young、女、孕、cutting needle、大 gauge",
     "Pencil-point (Whitacre/Sprotte) needle 可大幅降低 PDPH",
     "需鑑別 cortical vein thrombosis、subdural hematoma、preeclampsia"],
    "PDPH, blood patch",
    "Chestnut's Obstetric Anesthesia 6/e"),

# --- Sedation (1) ---
add("GP", "鎮靜深度",
    "下列何者最符合 Moderate Sedation (Conscious Sedation) 之定義？",
    [("A", "病人對 verbal command 有目的性反應、自主呼吸足夠、心血管功能維持"),
     ("B", "病人對 painful stimuli 無反應，呼吸需輔助"),
     ("C", "病人完全無反應、需 intubation"),
     ("D", "病人完全清醒")],
    "A",
    "ASA Sedation Continuum：(1) Minimal 對 verbal 正常反應；(2) Moderate 對 verbal/tactile 有目的反應、呼吸自主；(3) Deep 對 painful 有反應、呼吸可能需輔助；(4) General anesthesia 無反應。每階段都可能進展到更深，麻醉人員須能 rescue 一階。",
    ["Moderate sedation 常用：Midazolam + Fentanyl",
     "Dexmedetomidine 可達 cooperative sedation 無顯著呼吸抑制",
     "Propofol moderate dose 仍可能進入 deep sedation，需具備全麻 rescue 能力"],
    "Sedation continuum, MAC",
    "ASA Continuum of Depth of Sedation"),

# --- Pain (1) ---
add("GP", "急性疼痛",
    "Multimodal Analgesia 的核心概念為何？",
    [("A", "高劑量 opioid 為唯一選擇"),
     ("B", "Combine 不同作用機轉藥物 + 區域麻醉，降低 opioid 用量與副作用"),
     ("C", "NSAIDs 適用於所有病人"),
     ("D", "完全避免使用 opioid")],
    "B",
    "Multimodal = paracetamol + NSAIDs + gabapentinoid + ketamine + dexmedetomidine + regional anesthesia + opioid (rescue)；減少 opioid 用量、PONV、便秘、呼吸抑制；ERAS protocol 核心。",
    ["Enhanced Recovery After Surgery (ERAS) 強調 opioid-sparing",
     "Ketamine 0.1–0.5 mg/kg 為 NMDA antagonist 對 chronic pain 病人有效",
     "Regional anesthesia 是降低慢性術後疼痛的關鍵"],
    "Multimodal analgesia, ERAS",
    "Pocket Anesthesia 3/e, Ch. Pain Management"),

# ===== SURGICAL PROCEDURES / SPECIAL POPULATIONS (SP) - 30% target ~24 questions =====

# --- Cardiac (3) ---
add("SP", "心臟麻醉",
    "Severe Aortic Stenosis 病人麻醉之血流動力學目標，下列何者最為重要？",
    [("A", "維持 sinus rhythm、避免 tachycardia、避免低血壓、維持 SVR"),
     ("B", "Tachycardia 有助 cardiac output"),
     ("C", "降低 SVR 以減少 afterload"),
     ("D", "Hypovolemia 較佳")],
    "A",
    "Severe AS 病人 LV 已 hypertrophic、預載依賴、無法即時增加 stroke volume：sinus rhythm + 緩慢心率 (60–80) + 正常 preload + 充足 SVR (avoid hypotension)。Spinal anesthesia 因突然 sympathectomy 為相對禁忌。",
    ["Severe AS：AVA < 1 cm²、Mean gradient > 40、Peak velocity > 4 m/s",
     "Phenylephrine 維持 SVR 不增心率",
     "Coronary perfusion 嚴重依賴 diastolic pressure"],
    "Aortic stenosis, hemodynamic goal",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

add("SP", "ECMO",
    "VA-ECMO (Veno-Arterial ECMO) 主要適應症為何？",
    [("A", "單純嚴重 hypoxia"),
     ("B", "心肺同時衰竭、cardiogenic shock 無法以藥物控制"),
     ("C", "Sepsis 但循環穩定"),
     ("D", "輕度 hypotension")],
    "B",
    "VA-ECMO 提供 cardiopulmonary support，用於 cardiogenic shock、refractory cardiac arrest (ECPR)、massive PE、bridge to transplant。VV-ECMO 僅 respiratory support 用於 ARDS 等。",
    ["VA-ECMO 常見 LV distension 需 venting",
     "Anticoagulation: heparin ACT 180–220 sec",
     "出血、Limb ischemia、Harlequin syndrome 為併發症"],
    "ECMO, VA, cardiogenic shock",
    "Miller's Anesthesia 8/e, Ch. 67 Cardiac Surgery"),

add("SP", "Cardiac Tamponade",
    "Cardiac Tamponade 典型 Beck's Triad 為下列何者？",
    [("A", "Hypotension、Muffled heart sounds、Jugular venous distention"),
     ("B", "Hypertension、Bradycardia、Hyperventilation"),
     ("C", "Fever、Cough、Chest pain"),
     ("D", "Hypoxia、Hypercapnia、Acidosis")],
    "A",
    "Beck's Triad：低血壓 + 心音遙遠 + 頸靜脈怒張。Pulsus paradoxus > 10 mmHg、equalization of diastolic pressures、Kussmaul sign 也是線索。處置：心包穿刺、避免 IPPV 過早 (進一步壓迫)、維持 preload、HR、SVR、contractility。",
    ["麻醉誘導：ketamine + etomidate；保留自主呼吸",
     "Echo 為 diagnostic 與 procedural guidance",
     "Constrictive pericarditis 與 tamponade 不同，但血流動力相似"],
    "Cardiac tamponade, Beck's triad",
    "Miller's Anesthesia 8/e, Ch. 66 Cardiothoracic"),

# --- Thoracic (2) ---
add("SP", "單肺通氣",
    "One-Lung Ventilation (OLV) 期間，下列何項策略最有助於降低 hypoxia？",
    [("A", "高 PEEP (15 cmH₂O) 給 ventilated lung"),
     ("B", "Lung-protective ventilation: TV 4–6 mL/kg + 適度 PEEP + 100% FiO₂、可加 CPAP 於 nonventilated lung"),
     ("C", "停止 OLV 改 two-lung ventilation"),
     ("D", "高潮氣量 12 mL/kg")],
    "B",
    "OLV 策略：lung-protective ventilation (TV 4–6 mL/kg IBW、PEEP 5–10、recruitment maneuver)、FiO₂ as needed；hypoxia 處置：confirm DLT 位置、suction、increase FiO₂、PEEP、CPAP on non-ventilated、HPV (hypoxic pulmonary vasoconstriction)、必要時 clamp PA。",
    ["Double-lumen tube (DLT) 位置確認以 fiberoptic 為金標準",
     "Bronchial blocker 為 DLT 替代",
     "OLV-induced lung injury 為現代研究焦點"],
    "One-lung ventilation, lung protective",
    "Miller's Anesthesia 8/e, Ch. 65 Thoracic"),

add("SP", "氣管插管深度",
    "成人 ETT 插管後標準插管深度為何？",
    [("A", "牙齒對齊 14 cm"),
     ("B", "牙齒對齊 21 cm (女) / 23 cm (男)"),
     ("C", "牙齒對齊 27 cm"),
     ("D", "依吹氣量決定")],
    "B",
    "標準深度：成人女性 21 cm、男性 23 cm at lip；確認方式：bilateral breath sounds、symmetric chest rise、capnography、CXR (tip 2–3 cm above carina)。",
    ["過深 → 右主支氣管插管 (右肺通氣)",
     "過淺 → 拔管或漏氣",
     "頸部 flexion 使 ETT 深；extension 使其上移約 2 cm"],
    "ETT depth, mainstem intubation",
    "Hagberg Airway Management 4/e"),

# --- Neurosurgery (3) ---
add("SP", "神經外科",
    "TBI 病人麻醉處置目標為何？",
    [("A", "PaCO₂ 25–30 mmHg、SBP < 90、MAP < 60"),
     ("B", "PaCO₂ 35–40 mmHg、SBP > 100、MAP > 60、CPP 60–70 mmHg"),
     ("C", "PaCO₂ 50、避免 sedation"),
     ("D", "Aggressive hypothermia 至 28°C")],
    "B",
    "Brain Trauma Foundation 指引：避免 hypotension (SBP > 100 if 50–69 歲；> 110 if 15–49 或 >70)；避免 hypoxia (SpO₂ ≥ 90%、PaO₂ > 60)；CPP 60–70；hyperventilation 僅用於 acute herniation；中度體溫 (36–37)。",
    ["Hypotonic fluid (D5W、LR) 加重 cerebral edema，禁忌",
     "Mannitol 0.25–1 g/kg 或 Hypertonic saline 控制 ICP",
     "Nitrous Oxide 避免使用 (增加 cerebral metabolism、可能 air embolism)"],
    "TBI, CPP, brain trauma",
    "Brain Trauma Foundation Guidelines 4th edition"),

add("SP", "顱內手術擺位",
    "Sitting Position Craniotomy 之主要併發症為何？",
    [("A", "高血壓"), ("B", "Venous Air Embolism (VAE)"),
     ("C", "Hypothermia"), ("D", "Hyperglycemia")],
    "B",
    "Sitting position 顱內手術 VAE 發生率高達 25–45%。早期偵測：precordial Doppler、TEE、ETCO₂ 下降、ETN₂ 上升、SpO₂ 下降。處置：flood field with saline、jugular compression、aspirate from right atrium catheter、changing position。",
    ["其他併發症：postural hypotension、quadriplegia",
     "預防：充分 hydration、PFO 篩檢、適當 head 高度",
     "PFO 是禁忌 (paradoxical air embolism → CVA)"],
    "Sitting position, VAE",
    "Miller's Anesthesia 8/e, Ch. 70 Neurosurgical Anesthesia"),

add("SP", "頸動脈手術",
    "Carotid Endarterectomy (CEA) 期間，最重要的腦灌流監測方法為何？",
    [("A", "完全靠 SpO₂"),
     ("B", "Awake CEA 直接神經學評估；或 cerebral oximetry、EEG、SSEP、stump pressure"),
     ("C", "Routine intra-arterial CT angiography"),
     ("D", "BP cuff 即可")],
    "B",
    "CEA 期間頸動脈 cross-clamp 可能造成同側腦灌流不足。Gold standard 為 awake patient 神經評估 (regional anesthesia)；全麻時須 surrogate (rSO₂ NIRS、EEG、SSEP、stump pressure)。Shunt 使用視臨床指標。",
    ["術後血壓控制：避免 hyper-/hypoperfusion syndrome",
     "適當 PaCO₂ 35–40，避免 hyperventilation",
     "Shunt 可降低 stroke 風險但增加 dissection 風險"],
    "Carotid endarterectomy, neuromonitoring",
    "Miller's Anesthesia 8/e, Ch. 71 Vascular Surgery"),

# --- Orthopedic (2) ---
add("SP", "Tourniquet",
    "下肢手術使用 tourniquet 時，下列何者為「最常見」之全身副作用？",
    [("A", "Tourniquet 釋放後 hypertension"),
     ("B", "Tourniquet 釋放後 hypotension、hyperkalemia、酸中毒"),
     ("C", "Tourniquet 充氣時 hypoglycemia"),
     ("D", "Tourniquet 充氣時 bradycardia")],
    "B",
    "Tourniquet release 釋放堆積之 lactate、potassium、CO₂ 至全身循環 → transient hypotension、hyperkalemia、acidosis、ETCO₂ 升高。Tourniquet 時間 < 2 小時，定期釋放 reperfusion。",
    ["Tourniquet pain：充氣 45–60 分鐘後出現之 deep aching pain",
     "壓力：上肢 SBP+50、下肢 SBP+100 mmHg",
     "禁忌：嚴重 PAD、Sickle cell disease (相對)"],
    "Tourniquet, ischemia-reperfusion",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

add("SP", "脂肪栓塞",
    "下列何者最符合脂肪栓塞症候群 (Fat Embolism Syndrome) 之典型表現？",
    [("A", "Hyperthermia 與發疹"),
     ("B", "Hypoxemia + 神經症狀 + petechiae (24–72h 內出現)"),
     ("C", "立即 cardiac arrest"),
     ("D", "Hematuria 與血便")],
    "B",
    "Fat embolism syndrome 三主徵 (Gurd's criteria)：respiratory (hypoxemia、ARDS)、neurologic (confusion、coma)、cutaneous (petechiae)，常見於 long bone fracture、髖關節手術。處置：支持性、O₂、ventilation；類固醇與其他效果不一。",
    ["長骨骨折早期固定 (< 24h) 可降低風險",
     "其他 lab：FFA 上升、thrombocytopenia、fat in urine/sputum",
     "與 thromboembolism 不同；CT 表現 ground-glass、micronodule"],
    "Fat embolism, long bone fracture",
    "Pocket Anesthesia 3/e"),

# --- ENT / Ophthalmology (2) ---
add("SP", "扁桃腺切除",
    "扁桃腺切除 (Tonsillectomy) 術後出血為麻醉急症。麻醉誘導考量為何？",
    [("A", "標準 NPO 後施行 inhalation induction"),
     ("B", "視為 full stomach (吞入大量血液)、RSI、預備吸引、左側臥位、預備血品"),
     ("C", "完全等到 GI 排空"),
     ("D", "局部麻醉即可")],
    "B",
    "T&A 出血視為 full stomach + 可能 hypovolemia + difficult airway (blood、edema)：先 volume resuscitation、bloods、RSI 預備兩支 suction、可選 lateral position 防誤吸。經驗豐富之麻醉人員執行。",
    ["大型出血可能死亡，須警覺",
     "Etomidate 或 Ketamine 維持循環",
     "拔管前確保意識完全清醒、保護氣道反射"],
    "Tonsillectomy bleeding, RSI",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

add("SP", "眼科麻醉",
    "下列何種麻醉藥可顯著增加 Intraocular Pressure (IOP)？",
    [("A", "Propofol"), ("B", "Sevoflurane"),
     ("C", "Succinylcholine"), ("D", "Etomidate")],
    "C",
    "Succinylcholine 因 extraocular muscle 持續收縮使 IOP 上升 6–8 mmHg，於 open globe injury 屬相對禁忌；Rocuronium + reversal 為替代。多數靜脈藥與揮發藥降低 IOP。Ketamine 可能輕微上升。",
    ["Open globe injury 麻醉：RSI with rocuronium、避免咳嗽、嘔吐",
     "Oculocardiac reflex：眼外肌牽引引起 bradycardia，atropine 治療",
     "MAC 加 sub-Tenon block 為白內障常用組合"],
    "IOP, succinylcholine, open globe",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

# --- Obstetric (4) ---
add("SP", "孕婦生理變化",
    "下列關於孕婦麻醉生理變化之敘述，何者錯誤？",
    [("A", "Functional Residual Capacity (FRC) 下降"),
     ("B", "Oxygen consumption 上升"),
     ("C", "MAC 上升約 30%"),
     ("D", "Blood volume 上升 30–50%")],
    "C",
    "孕婦 MAC 「下降」約 30–40%。其他變化：FRC ↓ 20%、O₂ 消耗 ↑ 20%、minute ventilation ↑ 50%、CO ↑ 50%、blood volume ↑ 30–50%、aortocaval compression、physiologic anemia of pregnancy、hypercoagulable state。",
    ["快速 desaturation：FRC↓ + O₂ consumption↑",
     "Aortocaval compression：> 20 週應 left uterine displacement",
     "Difficult airway 風險：edema、breast、weight gain"],
    "Pregnancy physiology, MAC",
    "Chestnut's Obstetric Anesthesia 6/e"),

add("SP", "子癇前症",
    "重度子癇前症 (Severe Preeclampsia) 病人 MgSO₄ 治療之主要監測項目為何？",
    [("A", "Blood glucose"),
     ("B", "Deep tendon reflexes、respiratory rate、urine output、serum Mg level"),
     ("C", "EEG"),
     ("D", "Ferritin")],
    "B",
    "MgSO₄ 治療 preeclampsia (seizure prophylaxis) 之 toxicity 早期 → loss of DTRs (>8 mEq/L)、respiratory depression (>10)、cardiac arrest (>15)。監測 DTR、RR、UO、Mg 濃度 (target 4–8 mg/dL)；toxicity 處置 → IV calcium gluconate 1g。",
    ["Magnesium 同時 potentiate NMBA — 減量 50%",
     "Antihypertensive：Labetalol、Hydralazine、Nifedipine；避免 ACE-I",
     "Delivery 是 definitive treatment"],
    "Preeclampsia, MgSO4, toxicity",
    "Chestnut's Obstetric Anesthesia 6/e"),

add("SP", "剖腹產麻醉",
    "Elective Cesarean section 之首選麻醉方式為何？",
    [("A", "全身麻醉"),
     ("B", "Spinal anesthesia (subarachnoid block)"),
     ("C", "Local infiltration"),
     ("D", "Inhalational anesthesia by mask")],
    "B",
    "Elective CS 首選 spinal anesthesia：起效快、麻醉效果可靠、避免母體 airway 風險、新生兒暴露藥物少；epidural 適用於 labor analgesia 後直接延續或預期手術時間長。GA 用於 emergency、neuraxial 禁忌、failed regional。",
    ["Hypotension 預防：left lateral tilt、phenylephrine prophylaxis、co-load fluid",
     "Spinal dose：Bupivacaine 12 mg + fentanyl 15 µg + morphine 0.1 mg",
     "GA 時 RSI、預期 difficult airway、避免 anesthetic awareness"],
    "Cesarean section, spinal anesthesia",
    "Chestnut's Obstetric Anesthesia 6/e"),

add("SP", "羊水栓塞",
    "Amniotic Fluid Embolism (AFE) 典型表現為何？",
    [("A", "緩慢起病的 dyspnea"),
     ("B", "突發心血管虛脫 + hypoxemia + DIC，多於 labor 或 immediate postpartum 期間"),
     ("C", "頭痛 + 視覺模糊"),
     ("D", "Postpartum infection")],
    "B",
    "AFE 為產科急症：突發 cardiovascular collapse + respiratory failure + coagulopathy；致死率 > 60%。處置：高品質 CPR (若孕婦 perimortem CS within 4 min)、massive transfusion 1:1:1、advanced ICU、ECMO 考慮。",
    ["診斷為 clinical，無確診 lab；過去 fetal squames in pulmonary capillaries 已不再使用",
     "鑑別：PE、anaphylaxis、septic shock、anesthetic complication",
     "Atosiban、A-OK protocol (atropine、ondansetron、ketorolac) 為新興處置 (爭議)"],
    "Amniotic fluid embolism",
    "Chestnut's Obstetric Anesthesia 6/e"),

# --- Pediatric (4) ---
add("SP", "兒童氣道",
    "下列關於兒童 (< 8 歲) 氣道解剖之敘述，何者錯誤？",
    [("A", "頭大、舌大、頸短、會厭較長 U 型"),
     ("B", "Larynx 位置較高 (C3–C4)，比成人前傾"),
     ("C", "氣道最狹窄處為聲門 (Glottis)"),
     ("D", "枕部突出，自然 sniffing position")],
    "C",
    "兒童氣道最狹窄處為 cricoid ring (subglottic) — 此為傳統教科書教學，近年 MRI 研究顯示功能上仍是 glottis 最窄；但臨床上 cuffed ETT 選 size 時仍考慮 subglottic 較小的特性。",
    ["新生兒 ETT size: 內徑 mm = (年齡/4)+4 (uncuffed) 或 +3.5 (cuffed)",
     "Pediatric cuffed ETT 已普遍接受，降低需重新插管率",
     "MAC 嬰兒最高 (1 個月)，新生兒、早產兒則較低"],
    "Pediatric airway, cricoid",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

add("SP", "小兒誘導",
    "1 歲嬰兒無 IV、需 elective hernia repair。最常見的麻醉誘導方式為何？",
    [("A", "Inhalation induction with sevoflurane"),
     ("B", "強制建立 IV 後 propofol induction"),
     ("C", "Ketamine IM"),
     ("D", "Awake intubation")],
    "A",
    "嬰幼兒最常見 Sevoflurane inhalation induction (color、smell、無刺激)；待意識消失後建立 IV、給 NMBA、插管。Ketamine IM 用於 uncooperative、合作困難或 IV 困難情境。",
    ["Pre-induction：parental presence、midazolam 0.5 mg/kg PO",
     "8% Sevoflurane O₂/N₂O 開始；快速 induction",
     "兒童 stage 2 期間 laryngospasm/airway irritation 風險高"],
    "Pediatric induction, sevoflurane",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

add("SP", "兒童脫水",
    "5 kg 嬰兒因急性腸胃炎中度脫水 (10%)。下列何者為適當的初始 fluid resuscitation？",
    [("A", "D5W 100 mL/kg/h"),
     ("B", "Isotonic crystalloid (LR / 0.9% NaCl) 20 mL/kg bolus，重新評估"),
     ("C", "Hypertonic saline 3%"),
     ("D", "Colloid 50 mL/kg")],
    "B",
    "兒童脫水復甦：isotonic crystalloid 20 mL/kg bolus，必要時重複；同時計算 deficit + maintenance + ongoing loss 持續補充。10% 脫水 5 kg → deficit 500 mL，前 24 小時補一半。",
    ["Hypoglycemia 在嬰幼兒常見，加 D5 maintenance",
     "電解質：Na、K 監測，避免 hyponatremia (D5W maintenance 之風險)",
     "Shock 復甦：crystalloid → blood products if hemorrhagic"],
    "Pediatric fluid resuscitation",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

add("SP", "兒童藥物劑量",
    "兒童 IV induction 之 propofol 起始劑量約為何？",
    [("A", "0.5 mg/kg"), ("B", "1 mg/kg"),
     ("C", "2.5–3 mg/kg (兒童常用 induction dose)"),
     ("D", "5 mg/kg")],
    "C",
    "兒童 propofol induction dose 高於成人，約 2.5–3 mg/kg (versus 1.5–2.5 mg/kg in adults)；新生兒可能更高。其他兒童 IV induction options：ketamine 1–2 mg/kg、etomidate 0.3 mg/kg。",
    ["體積分布大、肝代謝快 → 兒童多數藥物 mg/kg 較高",
     "Propofol Infusion Syndrome 兒童風險高，避免長期 high-dose infusion",
     "Maintenance：propofol 100–250 µg/kg/min"],
    "Pediatric propofol",
    "Coté and Lerman's A Practice of Anesthesia for Infants and Children 6/e"),

# --- Geriatric (2) ---
add("SP", "老年麻醉",
    "下列關於老年病人麻醉處置之敘述，何者最為適當？",
    [("A", "麻醉劑量與年輕人相同"),
     ("B", "MAC 下降 6% 每 10 歲；藥物劑量需減量；謹防 polypharmacy interaction、postoperative delirium"),
     ("C", "可不必擔心 hypothermia"),
     ("D", "老年人 baroreflex 強，不易 hypotension")],
    "B",
    "老年生理變化：MAC↓ (每 10 歲 -6%)、心血管功能下降、腎肝代謝下降、骨骼肌減少、autoregulation 範圍縮小、polypharmacy。藥物劑量普遍下調 20–50%。預防：normothermia、多模式止痛、避免 benzodiazepine、early mobilization。",
    ["POD (Postoperative Delirium) 為老年常見併發症",
     "POCD (Postoperative Cognitive Dysfunction) 短長期均可能",
     "Frailty 為手術預後重要指標 (Clinical Frailty Scale)"],
    "Geriatric anesthesia, MAC, delirium",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

add("SP", "Postop Delirium",
    "下列何項策略最能降低老年術後譫妄 (Postoperative Delirium)？",
    [("A", "增加 benzodiazepine 劑量"),
     ("B", "避免 benzodiazepine、適當疼痛控制、normalize sleep、早期 mobilization、家屬參與"),
     ("C", "完全鎮靜以避免病人活動"),
     ("D", "Routine 大劑量 anticholinergics")],
    "B",
    "POD 預防 (HELP/ABCDEF bundle): 避免 deliriogenic drugs (benzo、anticholinergic、meperidine)、orient、daylight、glasses/hearing aids、early mobilization、avoid restraints、treat infection、family. 與年輕人比，老年 anesthetic-induced 譫妄延遲長。",
    ["Hyperactive、hypoactive、mixed 三型",
     "DSM-5 診斷：acute、fluctuating、attention 障礙、cognitive change",
     "Dexmedetomidine 可能優於 propofol 降低譫妄"],
    "Postoperative delirium prevention",
    "Miller's Anesthesia 8/e, Ch. 80 Geriatric Anesthesia"),

# --- Trauma / Critical (2) ---
add("SP", "創傷麻醉",
    "嚴重外傷病人 (ATLS 評估 grade III hemorrhagic shock) 之麻醉誘導劑選擇，何者最為合適？",
    [("A", "高劑量 propofol 2.5 mg/kg"),
     ("B", "Etomidate 0.3 mg/kg 或 Ketamine 1–2 mg/kg，並備好 vasopressor、massive transfusion"),
     ("C", "Fentanyl 5 µg/kg 為主，無 induction agent"),
     ("D", "Inhalation induction with sevoflurane")],
    "B",
    "Hemorrhagic shock 病人 propofol 可引起 cardiovascular collapse；Etomidate (hemodynamic stable) 或 Ketamine (循環支持) 較佳，須低劑量、慢推、配合 vasopressor 與 massive transfusion protocol (1:1:1) 同時進行。",
    ["Damage Control Resuscitation：permissive hypotension、early blood、limit crystalloid",
     "Tranexamic acid 早期 (< 3h) 1g IV 提升 survival",
     "ATLS：ABCDE 評估、primary/secondary survey"],
    "Trauma anesthesia, hemorrhagic shock",
    "Pocket Anesthesia 3/e"),

add("SP", "燒傷麻醉",
    "嚴重燒傷病人 (> 24h after injury) 使用 succinylcholine 之主要禁忌原因為何？",
    [("A", "Pseudocholinesterase deficiency"),
     ("B", "Up-regulated extrajunctional acetylcholine receptors → 致命性 hyperkalemia"),
     ("C", "支氣管痙攣"),
     ("D", "癲癇")],
    "B",
    "燒傷、長期臥床、去神經、嚴重感染 → extrajunctional AChR up-regulation。Succinylcholine 引起大量 K⁺ 外洩 → cardiac arrest。燒傷後 24h 起至 1–2 年內禁忌。Rocuronium 為替代 (劑量需增加因受體 up-regulation)。",
    ["燒傷對 nondepolarizing NMBA 有 resistance — 劑量需增加 2–3 倍",
     "氣道評估：face/neck burn 易迅速 swelling → 早期插管",
     "輸液：Parkland formula 4 mL × kg × %TBSA / 24h"],
    "Burn anesthesia, succinylcholine, hyperkalemia",
    "Miller's Anesthesia 8/e, Ch. 81 Trauma"),

# --- Hepatorenal (2) ---
add("SP", "腎衰竭",
    "ESRD 病人 (CrCl < 15) 麻醉用藥選擇，下列何者「最」需避免？",
    [("A", "Cisatracurium"),
     ("B", "Morphine (代謝物 M6G 蓄積)、Meperidine (Normeperidine 蓄積引起痙攣)"),
     ("C", "Propofol"),
     ("D", "Sevoflurane")],
    "B",
    "ESRD 病人腎排出之藥物與其代謝物蓄積 → 副作用延長。Morphine、Meperidine 為典型避免藥；Cisatracurium 經 Hofmann elimination 不依賴腎；Propofol、Sevoflurane 主要肝/腦代謝可用。",
    ["Fentanyl、Remifentanil 較安全",
     "Vecuronium 與 Rocuronium 腎衰時作用延長",
     "Sevoflurane Compound A 已不視為腎毒臨床問題 (low-flow)"],
    "ESRD, opioid, NMBA",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

add("SP", "肝衰竭",
    "嚴重肝硬化病人麻醉處置之關鍵考量，下列何者最為正確？",
    [("A", "肝代謝藥物之 clearance 不變"),
     ("B", "藥物分布體積與 protein binding 改變、albumin↓、coagulopathy、腦病、portal hypertension"),
     ("C", "凝血功能正常"),
     ("D", "可正常使用 high-dose acetaminophen")],
    "B",
    "肝硬化 → 藥物動力學顯著改變、Vd 增加、protein binding 下降、肝 clearance ↓、albumin ↓ 增加 free drug fraction。需顧及：encephalopathy 風險 (避免 benzo)、coagulopathy、varices、hepatorenal、portopulmonary HTN、ascites 影響 ventilation。",
    ["Acetaminophen ≤ 2 g/day 為限",
     "Atracurium / Cisatracurium 為首選 NMBA (Hofmann)",
     "Vasopressor 反應差，可能需 vasopressin 或 norepi"],
    "Cirrhosis, hepatic dysfunction",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

# --- Bariatric (1) ---
add("SP", "肥胖麻醉",
    "BMI 50 病人麻醉處置，下列何者最為適當？",
    [("A", "麻醉藥劑量依 total body weight 給予"),
     ("B", "Propofol induction 用 lean body weight；maintenance 用 ideal body weight；succinylcholine 用 total body weight"),
     ("C", "完全無需 preoxygenation"),
     ("D", "Supine 是最佳擺位")],
    "B",
    "肥胖病人藥物劑量：lipophilic (propofol、benzo、opioid maintenance) → LBW or IBW；hydrophilic (succinylcholine、NMBA) → TBW or LBW。Preoxygenation 必須完整、頭部抬高 25–30° (ramped position) 改善 laryngoscopy & FRC、預防 desaturation。",
    ["OSA 是常見伴隨症，預備 difficult airway",
     "PEEP 5–10 cmH₂O 維持 FRC、recruit",
     "預防 VTE：mechanical + chemical prophylaxis"],
    "Obesity, drug dosing, ramped position",
    "Stoelting's Anesthesia and Co-existing Disease 7/e"),

print_summary = True
if print_summary:
    cats = {}
    for q in Q:
        cats[q["category"]] = cats.get(q["category"], 0) + 1
    print(f"Total: {len(Q)} questions")
    for k, v in sorted(cats.items()):
        print(f"  {k}: {v}")

# Save
with open("/tmp/np-anesthesia/practice_questions.json", "w", encoding="utf-8") as f:
    json.dump(Q, f, ensure_ascii=False, separators=(',',':'))

import os
size = os.path.getsize("/tmp/np-anesthesia/practice_questions.json")
print(f"File size: {size/1024:.0f}KB")
